name: ROS2 CI FOR SYSTEM TESTS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy :
      fail-fast : false
      matrix:
        include:
          # Normal build (binary)
          - os: ubuntu-22.04
            distro: humble
            build-type: binary
          # Normal build (source)
          - os: ubuntu-22.04
            distro: humble
            build-type: source
           
    env:
      ROS2_REPOS_FILE_URL: 'https://raw.githubusercontent.com/ros2/ros2/${{ matrix.distro }}/ros2.repos'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup ROS and install binaries
        uses: ros-tooling/setup-ros@v0.6
        with:
          #required-ros-distributions: ${{ matrix.build-type == 'binary' && matrix.distro || '' }}
          required-ros-distributions: ${{ matrix.distro }}
          use-ros2-testing: true


      - name: Install other dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
              libignition-transport8-dev \

      - name: Source setup.bash
        run: |
          source /opt/ros/${{ matrix.distro }}/setup.bash
          ros2 run demo_nodes_cpp talker