name: ROS2 CI FOR SYSTEM TESTS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy :
      fail-fast : false

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup ROS and install binaries
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      - name: Source setup.bash
        run: |
          "source /opt/ros/humble/setup.bash && ros2 run --help"

      - name: Install Other ROS2 dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
              libignition-transport8-dev \
              ros-humble-turtlesim \

      - name: Build ROS 2 dependencies of voidwalking packages 
        uses : ros-tooling/action-ros-ci@v0.3
        with:      
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
          skip-tests: true
      

      - name: Launch Void Walker
        run: |
          ros2 run turtlesim turtlesim_node
    